import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Favourites() {
  return (
    <>
      <Head>
        <title>Mediabook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>To get started, edit the index.js file.</h1>
        <p>
          Text
        </p>
      </main>
    </>
  );
}