import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HomeContent from "@/components/HomeContent";
import { fetchFromTMDB } from "@/lib/tmdb";

export async function getServerSideProps() {
  try {
    const data = await fetchFromTMDB("/trending/movie/week");
    return {
      props: {
        trending: data.results ?? [],
        fetchError: null,
      },
    };
  } catch (e) {
    return {
      props: {
        trending: [],
        fetchError: e?.message ?? "Could not load trending movies.",
      },
    };
  }
}

export default function Home({ trending, fetchError }) {
  return (
    <>
      <Head>
        <title>Mediabook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Movies</h1>
        <HomeContent trending={trending} fetchError={fetchError} />
      </main>
    </>
  );
}
