import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { sampleData } from "@/sampleData";
import MovieList from "@/components/MovieList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mediabook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Sample Movie Data</h1>
        <MovieList movies={sampleData}/>
      </main>
    </>
  );
}
