'use client';
import { useRouter } from "next/router";
import { sampleData } from "@/sampleData";
import { useFavorites } from "@/context/FavoritesContext";
import LargeMovieCard from "@/components/LargeMovieCard";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function MovieDetails() {
  const router = useRouter();
  const { id } = router.query;
  const { favorites, addfavorite, removefavorite } = useFavorites();
  const movie = sampleData.find(item => item.imdbID === id);
  const isFav = movie && favorites.some(f => f.imdbID === movie.imdbID);

  if (!movie) return <p>Loading...</p>;

    
    return (
        <>
        <Head>
          <title>Mediabook</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <LargeMovieCard 
          movie={movie}
          isFavourite={isFav}
          setFavourite={() =>
          isFav
          ? removefavorite(movie.imdbID)
          : addfavorite(movie) } />
        </main>
        </>
    );
}