import { useRouter } from "next/router";
import { sampleData } from "@/sampleData";
import { useEffect, useState } from 'react';

import LargeMovieCard from "@/components/LargeMovieCard";
import Head from "next/head";
import styles from "@/styles/Home.module.css";


export default function MovieDetails() {
    
    const router = useRouter();
    console.log(router.query.id);
    
    const movieResult = sampleData.find((item) => item.imdbID == router.query.id);
    console.log(movieResult);
    
    const setFavourite = function() {
      
    }
    
    return (
        <>
        <Head>
          <title>Mediabook</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <LargeMovieCard movie={movieResult} isFavourite={false} setFavourite={setFavourite}/>
        </main>
        </>
    );
}