import { useRouter } from "next/router";
import { useParams } from "next/navigation";
import { useEffect, useState } from 'react';

import LargeMovieCard from "@/components/LargeMovieCard";
import Head from "next/head";
import styles from "@/styles/Home.module.css";


export default function MovieDetails() {
    const router = useRouter();
    console.log(router.query);
    
    return (
        <>
        <Head>
          <title>Mediabook</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <LargeMovieCard movie={1} />
        </main>
        </>
    );
}